
install.packages("data.table", type="binary")
install.packages("jsonlite", type="binary")
install.packages("stringr", type="binary")
install.packages("dplyr", type="binary")
install.packages("magrittr", type="binary")
install.packages("gutenbergr", type="binary")
install.packages("textdata", type="binary")
install.packages("tm", type="binary")
install.packages("tidytext", type="binary")
install.packages("janeaustenr", type="binary")
install.packages("ggplot2", type="binary")


require(data.table)
require(jsonlite)
require(stringr)
require(magrittr)
require(dplyr)
require(gutenbergr)
require(textdata)
require(tm)
require(tidytext)
require(janeaustenr)
require(ggplot2)
